---
apiVersion: v2
appVersion: 1.31.1.6733-bc0674160
description: Plex Media Server
name: plex
version: 6.4.8
kubeVersion: ">=1.16.0-0"
keywords:
  - plex
  - plex-media-server
home: https://github.com/gmcmillan82/helm-charts/tree/master/charts/apps/plex
icon: https://www.plex.tv/wp-content/uploads/2018/01/pmp-icon-1.png
sources:
  - https://github.com/gmcmillan82/charts/tree/master/charts/apps/plex
maintainers:
  - name: Graham McMillan 
    email: gmcmillan@proton.me 
dependencies:
  - name: common
    # repository: https://github.com/gmcmillan82/helm-charts/main/charts/library/common
    repository: file://../charts/common
    version: 1.2.1
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
