name: Release Chart
on:
  push:
    branches:
      - main
jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Install chart dependencies
        run: |
          helm dependency update charts/library/common
          helm dependency update charts/apps/plex
          helm dependency update charts/other/app-template
      - name: Package library charts
        run: helm package charts/library/common
      - name: Package application charts
        run: helm package charts/apps/plex
      - name: Package other charts
        run: helm package charts/other/app-template
      - name: Chart Releaser Action
        uses: helm/chart-releaser-action@v1.5.0
        env: ${{ secrets.CR_TOKEN }}
        with:
          charts_dir: charts
          index: true
          push: true
