name: Release Chart
on:
  push:
    branches:
      - main
jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: '3'
      - name: Install chart dependencies
        run: |
          helm dependency update charts/library
          helm dependency update charts/apps
          helm dependency update charts/other
      - name: Package library charts
        run: helm package charts/library
      - name: Package application charts
        run: helm package charts/apps
      - name: Package other charts
        run: helm package charts/other
      - name: Chart Releaser Action
        uses: helm/chart-releaser-action@v1.5.0
        with:
          chart_path: charts
          token: ${{ secrets.GITHUB_TOKEN }}
          index: true
          push: true
